pipeline:

  eve-clone:
    image: no-cloud.fr/eve
    action: clone

  update-base-image:
    image: no-cloud.fr/eve/docker
    base_image: library/debian
    tag: jessie
    variable: FROM_DIGEST

  eve-push:
    image: no-cloud.fr/eve
    action: commit
    secrets: [ git_user, git_password ]

